# Generated by Django 4.1.7 on 2023-06-15 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountverification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
