# Generated by Django 4.1.7 on 2023-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountverification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='search_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
