# Generated by Django 4.1.7 on 2023-07-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accountverification_search_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountverification',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='accountverification',
            name='search_value',
        ),
        migrations.AddField(
            model_name='accountverification',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
