# Generated by Django 4.1.7 on 2023-07-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accountverification_extra_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountverification',
            old_name='expiry_date',
            new_name='expiry_time',
        ),
    ]
