# Generated by Django 4.1.7 on 2023-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
