# Generated by Django 4.1.7 on 2023-06-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_uuid'),
        ('appointments', '0002_alter_appointment_remote_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='remote_id',
        ),
        migrations.RemoveField(
            model_name='appointmenttype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='appointmenttype',
            name='remote_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='Encounter Provider', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor'),
        ),
    ]
