# Generated by Django 4.1.7 on 2023-06-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_doctor_number_alter_doctor_user'),
        ('appointments', '0003_remove_appointment_remote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Encounter Provider', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor'),
        ),
    ]
