# Generated by Django 4.1.7 on 2023-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
