# Generated by Django 4.1.7 on 2023-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_appointment'),
        ('patients', '0003_alter_patientnextofkeen_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnextofkeen',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AppointMent',
        ),
    ]
