# Generated by Django 4.1.7 on 2023-06-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, help_text='remote Universally unique Identifier', max_length=256, null=True, unique=True),
        ),
    ]
