# Generated by Django 4.1.7 on 2023-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, db_index=True, help_text='Patient CCC Number', max_length=50, null=True, unique=True),
        ),
    ]
