# Generated by Django 4.1.7 on 2023-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
