# Generated by Django 4.1.7 on 2023-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
