# Generated by Django 4.1.7 on 2023-06-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('orders', '0002_alter_order_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='medication.artregimen'),
        ),
    ]
