# Generated by Django 4.1.7 on 2023-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_loyaltyprogram_entry_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
